spring.application.name=AUTH-SERVICE

server.port= 8082

logging.level.org.springframework.security=DEBUG

# Core Database Connection Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/microservice_users
spring.datasource.username=niraj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=Y2hlY2tzdGVhZHl0b3BzaG91dHZlcmJzdHJlYW10aGVyZWZvcmV0YWxlc3Bhc3NzdHI=
jwt.expiration=3600000
