# Application Name
spring.application.name=GATEWAY-SERVICE

# Server Port
server.port=8080

logging.level.org.springframework.security=DEBUG

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ----------------------------
# Routes
# ----------------------------

# Order Service
spring.cloud.gateway.server.webflux.routes[0].id=order-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/orders/**

# Inventory Service
spring.cloud.gateway.server.webflux.routes[1].id=inventory-service-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/app/v1/products/**

jwt.secret=Y2hlY2tzdGVhZHl0b3BzaG91dHZlcmJzdHJlYW10aGVyZWZvcmV0YWxlc3Bhc3NzdHI=








